/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SupportRouteImport } from './routes/support'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSplatRouteImport } from './routes/_app/$'
import { Route as AppAssignmentsRouteImport } from './routes/_app/assignments'
import { Route as AppAuditRouteImport } from './routes/_app/audit'
import { Route as AppCertificatesRouteImport } from './routes/_app/certificates'
import { Route as AppEnrollmentsRouteImport } from './routes/_app/enrollments'
import { Route as AppGradebookRouteImport } from './routes/_app/gradebook'
import { Route as AppInterviewPrepRouteImport } from './routes/_app/interview-prep'
import { Route as AppOrgsRouteImport } from './routes/_app/orgs'
import { Route as AppReportRouteImport } from './routes/_app/report'
import { Route as AppReviewQueueRouteImport } from './routes/_app/review-queue'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppStudentsRouteImport } from './routes/_app/students'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as VerifyCertCodeRouteImport } from './routes/verify.$certCode'
import { Route as AppCoursesIndexRouteImport } from './routes/_app/courses.index'
import { Route as AppReviewsSubmissionIdRouteImport } from './routes/_app/reviews.$submissionId'
import { Route as AppSubmissionsSubmissionIdRouteImport } from './routes/_app/submissions.$submissionId'
import { Route as AppCoursesCourseIdIndexRouteImport } from './routes/_app/courses.$courseId.index'
import { Route as AppCoursesCourseIdLessonsLessonIdRouteImport } from './routes/_app/courses.$courseId.lessons.$lessonId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const AppAssignmentsRoute = AppAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppCertificatesRoute = AppCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => AppRoute,
} as any)
const AppEnrollmentsRoute = AppEnrollmentsRouteImport.update({
  id: '/enrollments',
  path: '/enrollments',
  getParentRoute: () => AppRoute,
} as any)
const AppGradebookRoute = AppGradebookRouteImport.update({
  id: '/gradebook',
  path: '/gradebook',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewPrepRoute = AppInterviewPrepRouteImport.update({
  id: '/interview-prep',
  path: '/interview-prep',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgsRoute = AppOrgsRouteImport.update({
  id: '/orgs',
  path: '/orgs',
  getParentRoute: () => AppRoute,
} as any)
const AppReportRoute = AppReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewQueueRoute = AppReviewQueueRouteImport.update({
  id: '/review-queue',
  path: '/review-queue',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCertCodeRoute = VerifyCertCodeRouteImport.update({
  id: '/verify/$certCode',
  path: '/verify/$certCode',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCoursesIndexRoute = AppCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewsSubmissionIdRoute = AppReviewsSubmissionIdRouteImport.update({
  id: '/reviews/$submissionId',
  path: '/reviews/$submissionId',
  getParentRoute: () => AppRoute,
} as any)
const AppSubmissionsSubmissionIdRoute =
  AppSubmissionsSubmissionIdRouteImport.update({
    id: '/submissions/$submissionId',
    path: '/submissions/$submissionId',
    getParentRoute: () => AppRoute,
  } as any)
const AppCoursesCourseIdIndexRoute = AppCoursesCourseIdIndexRouteImport.update({
  id: '/courses/$courseId/',
  path: '/courses/$courseId/',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesCourseIdLessonsLessonIdRoute =
  AppCoursesCourseIdLessonsLessonIdRouteImport.update({
    id: '/courses/$courseId/lessons/$lessonId',
    path: '/courses/$courseId/lessons/$lessonId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/support': typeof SupportRoute
  '/$': typeof AppSplatRoute
  '/assignments': typeof AppAssignmentsRoute
  '/audit': typeof AppAuditRoute
  '/certificates': typeof AppCertificatesRoute
  '/enrollments': typeof AppEnrollmentsRoute
  '/gradebook': typeof AppGradebookRoute
  '/interview-prep': typeof AppInterviewPrepRoute
  '/orgs': typeof AppOrgsRoute
  '/report': typeof AppReportRoute
  '/review-queue': typeof AppReviewQueueRoute
  '/settings': typeof AppSettingsRoute
  '/students': typeof AppStudentsRoute
  '/users': typeof AppUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/verify/$certCode': typeof VerifyCertCodeRoute
  '/reviews/$submissionId': typeof AppReviewsSubmissionIdRoute
  '/submissions/$submissionId': typeof AppSubmissionsSubmissionIdRoute
  '/courses/': typeof AppCoursesIndexRoute
  '/courses/$courseId/': typeof AppCoursesCourseIdIndexRoute
  '/courses/$courseId/lessons/$lessonId': typeof AppCoursesCourseIdLessonsLessonIdRoute
}
export interface FileRoutesByTo {
  '/support': typeof SupportRoute
  '/$': typeof AppSplatRoute
  '/assignments': typeof AppAssignmentsRoute
  '/audit': typeof AppAuditRoute
  '/certificates': typeof AppCertificatesRoute
  '/enrollments': typeof AppEnrollmentsRoute
  '/gradebook': typeof AppGradebookRoute
  '/interview-prep': typeof AppInterviewPrepRoute
  '/orgs': typeof AppOrgsRoute
  '/report': typeof AppReportRoute
  '/review-queue': typeof AppReviewQueueRoute
  '/settings': typeof AppSettingsRoute
  '/students': typeof AppStudentsRoute
  '/users': typeof AppUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/verify/$certCode': typeof VerifyCertCodeRoute
  '/': typeof AppIndexRoute
  '/reviews/$submissionId': typeof AppReviewsSubmissionIdRoute
  '/submissions/$submissionId': typeof AppSubmissionsSubmissionIdRoute
  '/courses': typeof AppCoursesIndexRoute
  '/courses/$courseId': typeof AppCoursesCourseIdIndexRoute
  '/courses/$courseId/lessons/$lessonId': typeof AppCoursesCourseIdLessonsLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/support': typeof SupportRoute
  '/_app/$': typeof AppSplatRoute
  '/_app/assignments': typeof AppAssignmentsRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/certificates': typeof AppCertificatesRoute
  '/_app/enrollments': typeof AppEnrollmentsRoute
  '/_app/gradebook': typeof AppGradebookRoute
  '/_app/interview-prep': typeof AppInterviewPrepRoute
  '/_app/orgs': typeof AppOrgsRoute
  '/_app/report': typeof AppReportRoute
  '/_app/review-queue': typeof AppReviewQueueRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/students': typeof AppStudentsRoute
  '/_app/users': typeof AppUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/verify/$certCode': typeof VerifyCertCodeRoute
  '/_app/': typeof AppIndexRoute
  '/_app/reviews/$submissionId': typeof AppReviewsSubmissionIdRoute
  '/_app/submissions/$submissionId': typeof AppSubmissionsSubmissionIdRoute
  '/_app/courses/': typeof AppCoursesIndexRoute
  '/_app/courses/$courseId/': typeof AppCoursesCourseIdIndexRoute
  '/_app/courses/$courseId/lessons/$lessonId': typeof AppCoursesCourseIdLessonsLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/support'
    | '/$'
    | '/assignments'
    | '/audit'
    | '/certificates'
    | '/enrollments'
    | '/gradebook'
    | '/interview-prep'
    | '/orgs'
    | '/report'
    | '/review-queue'
    | '/settings'
    | '/students'
    | '/users'
    | '/auth/callback'
    | '/verify/$certCode'
    | '/reviews/$submissionId'
    | '/submissions/$submissionId'
    | '/courses/'
    | '/courses/$courseId/'
    | '/courses/$courseId/lessons/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/support'
    | '/$'
    | '/assignments'
    | '/audit'
    | '/certificates'
    | '/enrollments'
    | '/gradebook'
    | '/interview-prep'
    | '/orgs'
    | '/report'
    | '/review-queue'
    | '/settings'
    | '/students'
    | '/users'
    | '/auth/callback'
    | '/verify/$certCode'
    | '/'
    | '/reviews/$submissionId'
    | '/submissions/$submissionId'
    | '/courses'
    | '/courses/$courseId'
    | '/courses/$courseId/lessons/$lessonId'
  id:
    | '__root__'
    | '/_app'
    | '/support'
    | '/_app/$'
    | '/_app/assignments'
    | '/_app/audit'
    | '/_app/certificates'
    | '/_app/enrollments'
    | '/_app/gradebook'
    | '/_app/interview-prep'
    | '/_app/orgs'
    | '/_app/report'
    | '/_app/review-queue'
    | '/_app/settings'
    | '/_app/students'
    | '/_app/users'
    | '/auth/callback'
    | '/verify/$certCode'
    | '/_app/'
    | '/_app/reviews/$submissionId'
    | '/_app/submissions/$submissionId'
    | '/_app/courses/'
    | '/_app/courses/$courseId/'
    | '/_app/courses/$courseId/lessons/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SupportRoute: typeof SupportRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  VerifyCertCodeRoute: typeof VerifyCertCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$': {
      id: '/_app/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assignments': {
      id: '/_app/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AppAssignmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/certificates': {
      id: '/_app/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof AppCertificatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/enrollments': {
      id: '/_app/enrollments'
      path: '/enrollments'
      fullPath: '/enrollments'
      preLoaderRoute: typeof AppEnrollmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gradebook': {
      id: '/_app/gradebook'
      path: '/gradebook'
      fullPath: '/gradebook'
      preLoaderRoute: typeof AppGradebookRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/interview-prep': {
      id: '/_app/interview-prep'
      path: '/interview-prep'
      fullPath: '/interview-prep'
      preLoaderRoute: typeof AppInterviewPrepRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orgs': {
      id: '/_app/orgs'
      path: '/orgs'
      fullPath: '/orgs'
      preLoaderRoute: typeof AppOrgsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/report': {
      id: '/_app/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AppReportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/review-queue': {
      id: '/_app/review-queue'
      path: '/review-queue'
      fullPath: '/review-queue'
      preLoaderRoute: typeof AppReviewQueueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students': {
      id: '/_app/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$certCode': {
      id: '/verify/$certCode'
      path: '/verify/$certCode'
      fullPath: '/verify/$certCode'
      preLoaderRoute: typeof VerifyCertCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/courses/': {
      id: '/_app/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof AppCoursesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reviews/$submissionId': {
      id: '/_app/reviews/$submissionId'
      path: '/reviews/$submissionId'
      fullPath: '/reviews/$submissionId'
      preLoaderRoute: typeof AppReviewsSubmissionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/submissions/$submissionId': {
      id: '/_app/submissions/$submissionId'
      path: '/submissions/$submissionId'
      fullPath: '/submissions/$submissionId'
      preLoaderRoute: typeof AppSubmissionsSubmissionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses/$courseId/': {
      id: '/_app/courses/$courseId/'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId/'
      preLoaderRoute: typeof AppCoursesCourseIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses/$courseId/lessons/$lessonId': {
      id: '/_app/courses/$courseId/lessons/$lessonId'
      path: '/courses/$courseId/lessons/$lessonId'
      fullPath: '/courses/$courseId/lessons/$lessonId'
      preLoaderRoute: typeof AppCoursesCourseIdLessonsLessonIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppAssignmentsRoute: typeof AppAssignmentsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppCertificatesRoute: typeof AppCertificatesRoute
  AppEnrollmentsRoute: typeof AppEnrollmentsRoute
  AppGradebookRoute: typeof AppGradebookRoute
  AppInterviewPrepRoute: typeof AppInterviewPrepRoute
  AppOrgsRoute: typeof AppOrgsRoute
  AppReportRoute: typeof AppReportRoute
  AppReviewQueueRoute: typeof AppReviewQueueRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStudentsRoute: typeof AppStudentsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppReviewsSubmissionIdRoute: typeof AppReviewsSubmissionIdRoute
  AppSubmissionsSubmissionIdRoute: typeof AppSubmissionsSubmissionIdRoute
  AppCoursesIndexRoute: typeof AppCoursesIndexRoute
  AppCoursesCourseIdIndexRoute: typeof AppCoursesCourseIdIndexRoute
  AppCoursesCourseIdLessonsLessonIdRoute: typeof AppCoursesCourseIdLessonsLessonIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppAssignmentsRoute: AppAssignmentsRoute,
  AppAuditRoute: AppAuditRoute,
  AppCertificatesRoute: AppCertificatesRoute,
  AppEnrollmentsRoute: AppEnrollmentsRoute,
  AppGradebookRoute: AppGradebookRoute,
  AppInterviewPrepRoute: AppInterviewPrepRoute,
  AppOrgsRoute: AppOrgsRoute,
  AppReportRoute: AppReportRoute,
  AppReviewQueueRoute: AppReviewQueueRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStudentsRoute: AppStudentsRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
  AppReviewsSubmissionIdRoute: AppReviewsSubmissionIdRoute,
  AppSubmissionsSubmissionIdRoute: AppSubmissionsSubmissionIdRoute,
  AppCoursesIndexRoute: AppCoursesIndexRoute,
  AppCoursesCourseIdIndexRoute: AppCoursesCourseIdIndexRoute,
  AppCoursesCourseIdLessonsLessonIdRoute:
    AppCoursesCourseIdLessonsLessonIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SupportRoute: SupportRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  VerifyCertCodeRoute: VerifyCertCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
